#
# Makefile
#
# CC50
# Pset 5
#

all: recover

recover: recover.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o recover recover.c

recover2: recover2.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o recover2 recover2.c

clean:
	rm -f *.o a.out core.* recover
